INSERT INTO console (console, consolePrice, platform, itemDesc) VALUES 
        ("PlayStation 1", 32.91, "Playstation", "The PlayStation (abbreviated as PS, commonly known as the PS1 or its codename PSX) is a home video game console developed and marketed by Sony Computer Entertainment."),
        ("PlayStation 2", 90.99, "Playstation", "A popular video game console from Sony. DVD based and introduced in the U.S. in 2000 after great success in Japan, the first PS2 models came with a 128-bit, 300 MHz Emotion CPU."),
        ("PlayStation 3", 60.96, "Playstation", "A video game console from Sony that was introduced in late 2006. Containing a high-definition Blu-ray drive that also reads DVDs, CDs and SACD discs, the PS3 uses the Cell processor."),
        ("PlayStation 4", 309.98, "Playstation", "The PlayStation 4 is a home video game console developed by Sony Computer Entertainment. Announced as the successor to the PlayStation 3 and was it was launched on November 15, 2013, in North America."),
        ("PlayStation 5", 648.16, "Playstation", "The latest Sony PlayStation introduced in November 2020. Powered by an eight-core AMD Zen 2 CPU and custom AMD Radeon GPU"),
        ("PS VITA TV", 155.92,"Playstation", "The PlayStation TV (abbreviated to PS TV), known in Japan and other parts of Asia as the PlayStation Vita TV or PS Vita TV, is a microconsole, and a non-handheld variant of the PlayStation Vita"),
        ("NES", 46.04, "Nintendo", "The Nintendo Entertainment System (NES) is an 8-bit third-generation home video game console produced by Nintendo." ),
        ("SNES", 68.69, "Nintendo", "The Super Nintendo Entertainment System (SNES), commonly shortened to Super NES or Super Nintendo, is a 16-bit home video game console developed by Nintendo"),
        ("N64", 149.99, "Nintendo", "The Nintendo 64[a] (N64) is a home video game console developed by Nintendo. The successor to the Super Nintendo Entertainment System, it was released on June 23, 1996"),
        ("Game Cube", 56.76, "Nintendo", "The GameCube is a home video game console developed and released by Nintendo in Japan on September 14, 2001"),
        ("WII", 62.71, "Nintendo",  "The WII is a home video game console developed and marketed by Nintendo. It was released on November 19, 2006, in North America and in December 2006 for most other regions of the world"),
        ("WII U", 61.43, "Nintendo", "is a home video game console developed by Nintendo as the successor to the Wii. Released in late 2012, it is the first eighth-generation video game console."),
        ("SWITCH", 274.95, "Nintendo", "The Nintendo Switch[n] is a video game console developed by Nintendo and released worldwide in most regions on March 3, 2017"),
        ("Genesis", 38.78, "Sega", "The Sega Genesis, known as the Mega Drive[c] outside North America, is a 16-bit fourth-generation home video game console developed and sold by Sega."),
        ("Nomad", 244.89, "Sega", "The Genesis Nomad, also known as Sega Nomad, is a handheld game console manufactured by Sega and released in North America in October 1995. The Nomad is a portable variation of the Sega Genesis"),
        ("DreamCast", 98.72, "Sega", "The Dreamcast[a] is a home video game console released by Sega on November 27, it was the first in the sixth generation of video game consoles, preceding Sony's PlayStation 2."),
        ("Retron 77", 70.98, "Atari", "Atari 2600 emulator able to play the majority of the 2600 library"),
        ("XBox", 60.99, "Xbox", "The Xbox is a home video game console and the first installment in the Xbox series of video game consoles manufactured by Microsoft"),
        ("XBox 360", 125.98, "Xbox", "The Xbox 360 is a home video game console developed by Microsoft. As the successor to the original Xbox, it is the second console in the Xbox series. "),
        ("XBox One", 89.99, "Xbox", "The Xbox One is a home video game console developed by Microsoft. Announced in May 2013, it is the successor to Xbox 360 and the third base console in the Xbox series");

INSERT INTO dev (devName) VALUES 
    ("id Software"),
    ("MicroProse"),
    ("Atlus"),
    ("2k Games"),
    ("Bandi Namco"),
    ("Sony"),
    ("Bluepoint Games"),
    ("Team ASOBI"),
    ("Spike Chunsoft"),
    ("Nintendo"),
    ("Midway Games"),
    ("Monolith Software, Inc."),
    ("Stern Electronics, Inc."),
    ("Atari, Inc."),
    ("Sierra"),
    ("Lionhead Studios Ltd."),
    ("Bungie"),
    ("Bandi namco"),
    ("Bethesda Softworks"),
    ("Rockstar"),
    ("Sterling Silver Software"),
    ("Sega Technical Institute"),
    ("Sega"),
    ("Midway Games"),
    ("Project Soul"),
    ("Hitmaker");



INSERT INTO pub (pubName) VALUES
    ("Activision"),
    ("Atlus"),
    ("Irrational Games"),
    ("Level-5"),
    ("Sony Santa Monica"),
    ("Bluepoint Games"),
    ("Sony"),
    ("Spike Chunsoft"),
    ("Nintendo"),
    ("Rare"),
    ("Sega"),
    ("Atari, Inc."),
    ("Vivendi Games"),
    ("Microsoft Studios"),
    ("Bandi Namco"),
    ("Bethesda Softworks"),
    ("Tengen"),
    ("Midway"),
    ("Namco"),
    ("Rockstar");


INSERT INTO games ( amnt, title, year, dev_id, pub_id, console_id, img, price, platform, rating, region, gameDesc) VALUES 
    (8,"Quake II", 1997, 1, 1, 1, "https://www.mobygames.com/images/covers/l/239572-quake-ii-playstation-front-cover.jpg", 15.99, "PlayStation", "M", "Global", "Quake II isn't a direct sequel to Quake, it merely uses its name due to id feeling the game\'s fast-paced, tactile feel felt closer to a Quake game than a new franchise."),
    (8,"sid meier's civilization II", 1996, 2, 1, 1,"https://www.mobygames.com/images/covers/l/13080-sid-meier-s-civilization-ii-playstation-front-cover.jpg", 13.99, "PlayStation", "E", "US", "Sid Meier's Civilization II is a turn-based strategy video game in the Civilization series, developed and published by MicroProse."),
    (8,"Shin Megami Tensei: Persona 3 FES", 2007, 3, 2, 2, "https://www.mobygames.com/images/covers/l/112775-shin-megami-tensei-persona-3-fes-playstation-2-front-cover.jpg", 32.99, "PlayStation", "M", "Global", " Persona 3 FES contains an enhanced version of the original game, loaded with new Personas and cutscenes, a weapon synthesis system"),
    (8,"Shin Megami Tensei: Persona 4", 2008, 3, 2, 2, "https://www.mobygames.com/images/covers/l/133680-shin-megami-tensei-persona-4-playstation-2-front-cover.png", 33.99, "PlayStation", "M", "Global", "Persona 4 follows a group of high school students dealing with a mysterious TV channel dedicated to distorting and exaggerating the truth of who they are and their identities"),
    (8,"BioShock", 2007, 4, 3, 3, "https://www.mobygames.com/images/covers/l/141188-bioshock-playstation-3-front-cover.jpg", 20.99, "PlayStation", "M", "Global", "BioShock is a first-person shooter with role-playing game customization and stealth elements, and is similar to System Shock 2."),
    (8,"Ni No Kuni: Wrath of the White Witch", 2011, 5, 4, 3, "https://www.mobygames.com/images/covers/l/723492-ni-no-kuni-wrath-of-the-white-witch-playstation-3-front-cover.jpg", 15.89, "PlayStation", "E-10", "Global", "Ni no Kuni: Wrath of the White Witch is a role-playing game that uses a third-person perspective. Players complete quests—linear scenarios with set objectives—to progress through the story."),
    (8,"Persona 5 Royal", 2019, 3, 2, 4, "https://www.mobygames.com/images/covers/l/700945-persona-5-royal-playstation-4-other.jpg", 40.99, "PlayStation", "M", "Global", "Persona®5 Royal is packed with new characters, story depth, new locations to explore, & a new grappling hook mechanic for access to new areas"),
    (8,"God Of War", 2018, 6, 5, 4, "https://www.mobygames.com/images/covers/l/501232-god-of-war-playstation-4-front-cover.jpg", 20.69, "PlayStation", "M", "Global", "As mentor and protector to Atreus, a son determined to earn his respect, he is forced to deal with and control the rage that has long defined him while out in a very dangerous world with his son."),
    (8,"Deamon's Souls", 2020, 7, 6, 5, "https://www.mobygames.com/images/covers/l/710671-demon-s-souls-playstation-5-front-cover.jpg", 49.99, "PlayStation", "M", "Global", "Demon's Souls is an action role-playing game where players take on the role of an adventurer, whose gender and appearance are customized at the beginning of the game"),
    (8,"Astro's Playroom", 2020, 8, 7, 5, "https://www.mobygames.com/images/covers/l/704162-playstation-5-included-game-playstation-5-front-cover.png", 655.99, "PlayStation", "E", "Global", "Astro's Playroom is a 3D platformer in which the player controls the title character Astro Bot using the DualSense controller."),
    (8,"Persona 4 Golden", 2012, 3, 2, 6, "https://www.mobygames.com/images/covers/l/276137-persona-4-golden-ps-vita-front-cover.png", 60.89, "PlayStation", "M", "Global", "A coming of age story that sets the protagonist and his friends on a journey kickstarted by a chain of serial murders."),
    (8,"Danganronpa 2: Goodbye Despair", 2012, 9, 8, 6, "https://www.mobygames.com/images/covers/l/306414-danganronpa-2-goodbye-despair-ps-vita-front-cover.jpg", 40.98, "PlayStation", "M", "Global", "The protagonist Hajime Hinata is part of a group of high-school students who are trapped on a tropical island by their high school's headmaster Monokuma"),
    (8,"Metroid", 1986, 10, 6, 7, "https://www.mobygames.com/images/covers/l/16091-metroid-nes-front-cover.jpg", 420.69, "Nintendo", "E", "US", "Metroid is an action-adventure game in which the player controls Samus Aran in sprite-rendered two-dimensional landscapes."),
    (8,"Super Mario Bros. / Duck Hunt", 1984, 10, 9, 7, "https://www.mobygames.com/images/covers/l/809988-super-mario-bros-duck-hunt-nes-manual.png", 5.99, "Nintendo", "E", "US", "Duck Hunt is a shooter game in which the objective is to shoot moving targets on the television screen in mid-flight. "),
    (8,"Pilotwings", 1990, 10, 10, 8, "https://www.mobygames.com/images/covers/l/24153-pilotwings-snes-front-cover.jpg", 3.99, "Nintendo", "E", "US", "Pilotwings is an amateur flight simulator game in which the player attempts to earn pilot licenses through lessons in light plane flight"),
    (8,"Donkey Kong Country 2: Diddy's Kong Quest", 1995, 10, 9, 8, "https://www.mobygames.com/images/covers/l/13360-donkey-kong-country-2-diddy-s-kong-quest-snes-front-cover.jpg", 8.50, "Nintendo", "E", "US", "the game stars Diddy Kong, as he and his girlfriend, Dixie Kong, make their way through Crocodile Isle to save Donkey Kong"),
    (8,"Rampage: World Tour", 1997, 11, 20, 9, "https://www.mobygames.com/images/covers/l/448945-rampage-world-tour-nintendo-64-front-cover.jpg", 2.50, "Nintendo", "T", "US", "Rampage World Tour is a game that was released in arcades, the Nintendo 64, and the Game Boy Color. It is a sequel to the popular classic arcade game Rampage"),
    (8,"Star Fox 64", 1997, 10, 9, 9, "https://www.mobygames.com/images/covers/l/6132-star-fox-64-nintendo-64-front-cover.jpg", 8.50, "Nintendo", "KA", "US", "Star Fox 64 is a 3D rail shooter game in which the player controls one of the vehicles piloted by Fox McCloud, usually an Arwing."),
    (8,"Super Mario Sunshine", 2002, 10, 9, 10, "https://www.mobygames.com/images/covers/l/14217-super-mario-sunshine-gamecube-front-cover.jpg", 4.50, "Nintendo", "E", "Global", "Super Mario Sunshine is a 3D platformer where players control Mario in an open environment in a similar manner to its predecessor, Super Mario 64"),
    (8,"The Legend of Zelda: Twilight Princess", 2006, 10, 9, 10, "https://www.mobygames.com/images/covers/l/795647-the-legend-of-zelda-twilight-princess-gamecube-front-cover.jpg", 3.99, "Nintendo", "T", "Global", "Join Link, along with the help of a new and mysterious character Midna, to discover why the land of Hyrule is being engulfed by a mysterious darkness known as the Twilight."),
    (8,"WII Sports Resort", 2009, 10, 9, 11, "https://www.mobygames.com/images/covers/l/159911-wii-sports-resort-wii-front-cover.jpg", 2.60, "Nintendo", "E", "US", " is a 2009 sports simulation video game developed and published by Nintendo for the Wii video game console, and is a sequel to Wii Sports."),
    (8,"Super Mario: Galaxy", 2007, 10, 9, 11, "https://www.mobygames.com/images/covers/l/153990-super-mario-galaxy-wii-front-cover.png", 4.90, "Nintendo", "E", "US", "Super Mario Galaxy is set in outer space, where Mario travels through different galaxies to collect Power Stars, earned by completing missions, defeating a boss, or reaching a particular area"),
    (8,"Xenoblade Chronicles X", 2015, 12, 9, 12, "https://www.mobygames.com/images/covers/l/317243-xenoblade-chronicles-x-wii-u-front-cover.png", 40.50, "Nintendo", "T", "US", "Xenoblade Chronicles X is an open world action role-playing video game developed by Monolith Soft and published by Nintendo for the Wii U console"),
    (8,"Sonic Lost World", 2013, 27, 11, 12, "https://www.mobygames.com/images/covers/l/309969-sonic-lost-world-wii-u-front-cover.jpg", 3.99, "NIntendo", "E-10", "Global", "is a platform game with action-adventure elements, in which the player controls Sonic the Hedgehog as he travels across the Lost Hex in order to rescue captured animals and stop the Deadly Six."),
    (8,"Super Mario: 3D All-Stars", 2020, 10, 9, 13, "https://www.mobygames.com/images/covers/l/684885-super-mario-3d-all-stars-nintendo-switch-front-cover.jpg", 13.99, "Nintendo", "E", "Global", "Super Mario 3D All-Stars is a 2020 compilation of platform games for the Nintendo Switch. It commemorates the 35th anniversary of Nintendo's Super Mario franchise"),
    (8,"Legend Of Zelda: Breath of the Wild", 2017, 10, 9, 13, "https://www.mobygames.com/images/covers/l/541221-the-legend-of-zelda-breath-of-the-wild-nintendo-switch-front-cover.jpg", 7.99, "Nintendo", "T", "Global", "The game is an installment of The Legend of Zelda series and is set at the end of its timeline."),
    (8,"Road Blasters", 1992, 21, 17, 14, "https://www.mobygames.com/images/covers/l/272266-roadblasters-genesis-front-cover.jpg", 3.99, "Sega", "T", "JP", "RoadBlasters is a combat racing video game released in arcades by Atari Games in 1987. In RoadBlasters, the player must navigate an armed sports car through 50 different rally races"),
    (8,"Sonic The Hedghog 2", 1992, 22, 11, 14, "https://www.mobygames.com/images/covers/l/13116-sonic-the-hedgehog-2-genesis-front-cover.jpg", 4.99, "Sega", "E", "US", "Sonic the Hedgehog 2 is a side-scrolling platform game. It features a story similar to the first Sonic the Hedgehog's"),
    (8,"Mortal Kombat 3", 1995, 10, 18, 14, "https://www.mobygames.com/images/covers/l/30582-mortal-kombat-3-genesis-front-cover.jpg", 0.50, "Sega", "M", "EU", "The third installment of Mortal Kombat retains the blood and gory attacks that defined the series. It introduces new types of the Fatality finishing moves, including Animalities."),
    (8,"Sega 6-Pak", 1995, 23, 11, 14, "https://www.mobygames.com/images/covers/l/12998-6-pak-genesis-front-cover.jpg", 3.99, "Sega", "KA", "US", "is a compilation featuring 6 Sega Genesis games, released in June 1995. This compilation features some of Sega's most successful games from the first year of the console."),
    (8,"Soul Calibur", 1998, 25, 19, 16, "https://www.mobygames.com/images/covers/l/7154-soulcalibur-dreamcast-front-cover.jpg", 2.50, "Sega", "T", "US", "is a weapon-based fighting video game franchise by Bandai Namco Entertainment."),
    (8,"Crazy Taxi", 1999, 26, 11, 16, "https://www.mobygames.com/images/covers/l/5801-crazy-taxi-dreamcast-front-cover.jpg", 4.30, "Sega", "T", "US", "The player controls one of several taxi drivers in a fictional city, looking for fares and then taking them to their destination in the fastest time possible."),
    (8,"Berzerk", 1980, 13, 12, 17, "https://www.mobygames.com/images/covers/l/27347-berzerk-atari-5200-front-cover.jpg", 2.99, "Atari", "KA", "US", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique nostrum odio illum assumenda quas vitae, necessitatibus consequatur deserunt dolore? Perferendis voluptatibus cupiditate aliquid."),
    (8,"Missile Command", 1980, 14, 12, 17, "https://www.mobygames.com/images/covers/s/413550-missile-command-atari-8-bit-manual.jpg", 1.50, "Atari", "KA", "US", "Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique nostrum odio illum assumenda quas vitae, necessitatibus consequatur deserunt dolore? Perferendis voluptatibus cupiditate aliquid."),
    (8,"Robots", 2005, 15, 13, 18, "https://www.mobygames.com/images/covers/l/95588-robots-xbox-front-cover.jpg", 2.50, "Xbox", "E", "EU", "Gamers will plays as Rodney as he moves to the big city to work for the company founded by his childhood hero."),
    (8,"Fable", 2008, 16, 14, 18, "https://www.mobygames.com/images/covers/l/36780-fable-xbox-front-cover.jpg", 7.80, "Xbox", "M", "US", "Fable is a role-playing video game where players control their character from a third-person perspective. The main character, known as The Hero of Oakvale"),
    (8,"Halo Reach", 2010, 17, 14, 19, "https://www.mobygames.com/images/covers/l/207192-halo-reach-xbox-360-front-cover.jpg", 30.50, "Xbox", "M", "US", "Halo: Reach is a first-person shooter in which players predominantly experience gameplay from a first-person perspective;"),
    (8,"Dragon Ball: Raging Blast 2", 2010, 5, 15, 19, "https://www.mobygames.com/images/covers/l/321091-dragon-ball-raging-blast-2-xbox-360-front-cover.jpg", 2.50, "Xbox", "T", "Global", "more than 90 playable characters, signature moves, transformation, and tons of bonus content, Dragon Ball: Raging Blast 2 turns up the intensity to create an authentic fighting experience.");

INSERT INTO review (f_name, l_name, email, phone, comment) VALUES
    ("John", "Doe", "johndoe0909@memail.com", 5558889999, "Good people good service one problem the game that i bought came in 2 days late but besides that not to bad"),
    ("Jane", "Doe", "janethemane@notmail.com", 5558889999, "Services were good they had my husbands game packages and sent off in like 2 min of me ordering will be shopping here agian"),
    ("Liz", "Goldenshoe", "lizthebiz@mail.com", 8675309999, "THIS IS A SCAM NEVER BUY FROM THIS STORE ALL THE PEOPLE WITH GOOD THINGS TO SAY WERE PAYED OFF THEY HAVE MY SON HELD CAPTIVE"),
    ("Json", "Goldenshoe", "golden.json@mail.com", 8889990000, "Dont listen to my mother she is liying, im not heald captive mom i just dont like your cooking thats all gosh"),
    ("Dan", "Shows", "danshows@noonecares.com", 5555555555, "They have good games from back when I was a kid not the crap that they make now adays. just good old games"),
    ("Ann", "Dante", "ad@genz.org", 4445557777, "As a gen-z i cannot like this establishment but i do not hate it that is the best i can say"),
    ("Lora", "Waters", "WatersL@yomama.com", 4449991111, "they have some of the cleanest consoles on the internet, and a very clean store"),
    ("Karen", "Karen", "karenK@humangarbage.com", 6666666666, "they were disrespectful and evil they are from the devil and so are the hethan games that they sell all a bunch of devil people");

INSERT INTO questions (f_name, l_name, email, phone, comment) VALUES
    ("John", "Doe", "johndoe0909@memail.com", 5558889999, "How do I know when the best time to order is, do you have black friday deals?"),
    ("Jane", "Doe", "janethemane@notmail.com", 5558889999, "How can i keep this secrit from my huband for his birthday"),
    ("Liz", "Goldenshoe", "lizthebiz@mail.com", 8675309999, "Regarding the releace of my son: life is better without that noise bratt yall keep him"),
    ("Json", "Goldenshoe", "golden.json@mail.com", 8889990000, "mom i want to come home, they said that you dont want me back is that true i hate you"),
    ("Dan", "Shows", "danshows@noonecares.com", 5555555555, "WHEN DID YALL START SELLING NEW GAMES, IT WAS JUST SUPPOSED TO BE THE GOLDEN ERA OF GAMES BETRAYERS"),
    ("Ann", "Dante", "ad@genz.org", 4445557777, "Do you sell anything besides games, gosh get with the times"),
    ("Lora", "Waters", "WatersL@yomama.com", 4449991111, "My payment for cleaning the store and the consoles?"),
    ("Karen", "Karen", "karenK@humangarbage.com", 6666666666, "WHEN WILL YOU STOP BEING DEVIL PEOPLE!!!!!!");

INSERT INTO app (f_name, l_name, email, phone, prev_work, refrence, refrence_phone, comment) VALUES 
    ("Json", "Goldenshoe", "golden.json@mail.com", 8889990000, "none", "none", "none", "I have been a loyal shopper of your for a long time i would love to get a job here if you have an opening");